spring.datasource.url=jdbc:postgresql://localhost:5432/Mobile_Backend_Application
spring.datasource.username=postgres
spring.datasource.password=Krishna@19

server.port=8083
s
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

jwt.secret=${TEST_JWT_SECRET}

logging.level.com.krishna.MobileBackendProjectPhase1=INFO